# Generated by Django 5.0.1 on 2024-02-21 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=20, verbose_name="nickname")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PageResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_1_responses", models.TextField()),
                ("page_2_responses", models.TextField()),
                ("page_3_responses", models.TextField()),
                ("page_4_responses", models.TextField()),
                ("page_5_responses", models.TextField()),
                ("page_6_responses", models.TextField()),
                ("quiz", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="portal.user"
                    ),
                ),
            ],
        ),
    ]
