# Generated by Django 4.1.7 on 2024-03-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email_code",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("code", models.CharField(max_length=6, verbose_name="code")),
                (
                    "create_data",
                    models.DateTimeField(auto_now_add=True, verbose_name="create date"),
                ),
                (
                    "expiration_data",
                    models.DateTimeField(verbose_name="expiration date"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="icon",
            field=models.FileField(
                default="image/1.jpg", upload_to="image", verbose_name="icon"
            ),
        ),
    ]
