# Generated by Django 4.1.7 on 2024-03-09 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0005_recipe_favorite_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favorite",
            name="recipe_id",
        ),
        migrations.RemoveField(
            model_name="favorite",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="user_id",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
    ]
