# Generated by Django 4.1.7 on 2024-03-09 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portal", "0007_recipe_favorite_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="create_data",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 10, 2, 49, 44, 267619),
                verbose_name="create date",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="r_imagefield",
            field=models.FileField(
                default="field/11.jpg", upload_to="field", verbose_name="imagefield"
            ),
        ),
    ]
